name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    label: 'enhancement'
  - title: '🐛 Bug Fixed'
    label: 'bug'
  - title: 'ETC'
    label: 'documentation'
change-template: '- $TITLE #$NUMBER @$AUTHOR '
template: |
  ## What's Changed
  $CHANGES

  **Full Changelog**: https://github.com/SENSE-IM/sense-turbo/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
