name: Slack Notification for PR

on:
  pull_request:
    branches:
      - dev
    types:
      - opened
      - reopened
      - synchronize

jobs:
  send-slack-notification-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get PR information
        id: get_pr_info
        env:
          SLACK_USER_MAPPING: ${{ secrets.SLACK_USER_ID_JSON }}
        run: |
          PR_NUMBER=${{ github.event.number }}
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_URL=${{ github.event.pull_request.html_url }}
          PR_BODY="${{ github.event.pull_request.body }}"
          
          # PR의 리뷰어 추출 및 Slack 멘션 형식으로 변환
          REVIEWERS=$(echo "${{ toJson(github.event.pull_request.requested_reviewers) }}" | jq -r '.[].login' | while read -r username; do
            slack_id=$(echo $SLACK_USER_MAPPING | jq -r ".[\"$username\"] // \"$username\"")
            if [ "$slack_id" != "$username" ]; then
              echo "<@$slack_id>"
            else
              echo "@$username"
            fi
          done | tr '\n' ' ' | sed 's/\s*$//')
          
          # 리뷰어가 없는 경우 처리
          if [ -z "$REVIEWERS" ]; then
            REVIEWERS="없음"
          fi
          
          # PR 본문에서 @멘션 추출 (@ 유지)
          MENTIONED_USERS=$(echo "$PR_BODY" | grep -o '@[[:alnum:]-]*' | tr '\n' ' ' | sed 's/\s*$//')
          
          # 멘션된 사용자가 없는 경우 처리
          if [ -z "$MENTIONED_USERS" ]; then
            MENTIONED_USERS="없음"
          fi

          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV
          echo "PR_URL=$PR_URL" >> $GITHUB_ENV
          echo "PR_REVIEWERS=$REVIEWERS" >> $GITHUB_ENV
          echo "PR_MENTIONED_USERS=$MENTIONED_USERS" >> $GITHUB_ENV

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: ${{ secrets.SLACK_DEPLOY_CHANNEL_ID }}
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🔄 PR 알림",
                    "emoji": true
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*PR 제목:* ${{ env.PR_TITLE }}\n*PR 링크:* <${{ env.PR_URL }}>\n*멘션된 사람:* ${{ env.PR_MENTIONED_USERS }}"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "emoji": true,
                        "text": "PR 보기"
                      },
                      "url": "${{ env.PR_URL }}",
                      "value": "view_pr"
                    }
                  ]
                }
              ]
            }