name: Slack Notification for PR

on:
  pull_request:
    branches:
      - dev
    types:
      - opened
      - reopened
      - synchronize

jobs:
  send-slack-notification-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get PR information
        id: get_pr_info
        run: |
          PR_NUMBER=${{ github.event.number }}
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_URL=${{ github.event.pull_request.html_url }}
          PR_BODY="${{ github.event.pull_request.body }}"
          
          # 리뷰어 추출
          REVIEWERS=""
          for reviewer in $(echo '${{ toJSON(github.event.pull_request.requested_reviewers) }}' | jq -r '.[].login'); do
            if [ -z "$REVIEWERS" ]; then
              REVIEWERS="<@$reviewer>"
            else
              REVIEWERS="$REVIEWERS <@$reviewer>"
            fi
          done

          # PR 본문에서 @멘션 추출
          MENTIONED_USERS=$(echo "$PR_BODY" | grep -o '@[[:alnum:]-]*' | tr '\n' ' ' | sed 's/@/<@/g')
          
          # 최종 멘션 문자열 생성
          FINAL_MENTIONS=""
          if [ ! -z "$REVIEWERS" ]; then
            FINAL_MENTIONS="리뷰어: $REVIEWERS"
          fi
          if [ ! -z "$MENTIONED_USERS" ]; then
            if [ ! -z "$FINAL_MENTIONS" ]; then
              FINAL_MENTIONS="$FINAL_MENTIONS\n멘션: $MENTIONED_USERS"
            else
              FINAL_MENTIONS="멘션: $MENTIONED_USERS"
            fi
          fi
          
          # 아무도 멘션되지 않은 경우
          if [ -z "$FINAL_MENTIONS" ]; then
            FINAL_MENTIONS="없음"
          fi

          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV
          echo "PR_URL=$PR_URL" >> $GITHUB_ENV
          echo "PR_MENTIONED_USERS=$FINAL_MENTIONS" >> $GITHUB_ENV

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: ${{ secrets.SLACK_DEPLOY_CHANNEL_ID }}
          payload: |
            {
              "text": "PR #${{ env.PR_NUMBER }} - \"${{ env.PR_TITLE }}\" 가 dev 브랜치에 제출되었습니다.",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*PR 제목:* \"${{ env.PR_TITLE }}\"\n*PR 링크:* <${{ env.PR_URL }}>\n*멘션된 사람:* \"${{ env.PR_MENTIONED_USERS }}\""
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "emoji": true,
                        "text": "PR 보기"
                      },
                      "url": "${{ env.PR_URL }}",
                      "value": "view_pr"
                    }
                  ]
                }
              ]
            }